--------------------------------------------------------
--  File created - Monday-November-28-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AIRPORTCITY
--------------------------------------------------------

  CREATE TABLE "AIRPORTCITY" 
   (	"AIRPORT" VARCHAR2(26 BYTE), 
	"CITY" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT);
REM INSERTING into AIRPORTCITY
SET DEFINE OFF;
Insert into AIRPORTCITY (AIRPORT,CITY) values ('ABE','Allentown/Bethlehem/Easton, PA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('ABQ','Albuquerque, NM');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('ABR','Aberdeen, SD');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('ABY','Albany, GA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('ACT','Waco, TX');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('ACV','Arcata/Eureka, CA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('ACY','Atlantic City, NJ');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('ADK','Adak Island, AK');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('ADQ','Kodiak, AK');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('AEX','Alexandria, LA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('AGS','Augusta, GA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('ALB','Albany, NY');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('AMA','Amarillo, TX');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('ANC','Anchorage, AK');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('APN','Alpena, MI');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('ASE','Aspen, CO');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('ATL','Atlanta, GA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('ATW','Appleton, WI');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('AUS','Austin, TX');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('AVL','Asheville, NC');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('AVP','Scranton/Wilkes-Barre, PA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('AZO','Kalamazoo, MI');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('BDL','Hartford, CT');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('BET','Bethel, AK');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('BFL','Bakersfield, CA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('BGM','Binghamton, NY');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('BGR','Bangor, ME');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('BHM','Birmingham, AL');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('BIL','Billings, MT');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('BIS','Bismarck/Mandan, ND');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('BJI','Bemidji, MN');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('BLI','Bellingham, WA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('BMI','Bloomington/Normal, IL');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('BNA','Nashville, TN');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('BOI','Boise, ID');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('BOS','Boston, MA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('BPT','Beaumont/Port Arthur, TX');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('BQK','Brunswick, GA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('BQN','Aguadilla, PR');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('BRD','Brainerd, MN');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('BRO','Brownsville, TX');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('BRW','Barrow, AK');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('BTM','Butte, MT');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('BTR','Baton Rouge, LA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('BTV','Burlington, VT');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('BUF','Buffalo, NY');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('BUR','Burbank, CA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('BWI','Baltimore, MD');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('BZN','Bozeman, MT');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('CAE','Columbia, SC');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('CAK','Akron, OH');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('CDC','Cedar City, UT');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('CDV','Cordova, AK');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('CHA','Chattanooga, TN');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('CHO','Charlottesville, VA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('CHS','Charleston, SC');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('CID','Cedar Rapids/Iowa City, IA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('CIU','Sault Ste. Marie, MI');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('CLE','Cleveland, OH');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('CLL','College Station/Bryan, TX');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('CLT','Charlotte, NC');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('CMH','Columbus, OH');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('CMX','Hancock/Houghton, MI');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('COD','Cody, WY');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('COS','Colorado Springs, CO');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('CPR','Casper, WY');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('CRP','Corpus Christi, TX');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('CRW','Charleston/Dunbar, WV');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('CSG','Columbus, GA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('CVG','Cincinnati, OH');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('CWA','Mosinee, WI');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('DAB','Daytona Beach, FL');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('DAL','Dallas, TX');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('DAY','Dayton, OH');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('DCA','Washington, DC');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('DEN','Denver, CO');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('DFW','Dallas/Fort Worth, TX');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('DHN','Dothan, AL');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('DLH','Duluth, MN');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('DRO','Durango, CO');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('DSM','Des Moines, IA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('DTW','Detroit, MI');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('DVL','Devils Lake, ND');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('EAU','Eau Claire, WI');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('ECP','Panama City, FL');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('EGE','Eagle, CO');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('EKO','Elko, NV');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('ELM','Elmira/Corning, NY');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('ELP','El Paso, TX');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('ERI','Erie, PA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('ESC','Escanaba, MI');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('EUG','Eugene, OR');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('EVV','Evansville, IN');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('EWN','New Bern/Morehead/Beaufort, NC');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('EWR','Newark, NJ');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('EYW','Key West, FL');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('FAI','Fairbanks, AK');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('FAR','Fargo, ND');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('FAT','Fresno, CA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('FAY','Fayetteville, NC');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('FCA','Kalispell, MT');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('FLG','Flagstaff, AZ');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('FLL','Fort Lauderdale, FL');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('FNT','Flint, MI');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('FSD','Sioux Falls, SD');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('FSM','Fort Smith, AR');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('FWA','Fort Wayne, IN');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('GCC','Gillette, WY');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('GEG','Spokane, WA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('GFK','Grand Forks, ND');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('GJT','Grand Junction, CO');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('GNV','Gainesville, FL');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('GPT','Gulfport/Biloxi, MS');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('GRB','Green Bay, WI');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('GRK','Killeen, TX');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('GRR','Grand Rapids, MI');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('GSO','Greensboro/High Point, NC');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('GSP','Greer, SC');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('GTF','Great Falls, MT');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('GTR','Columbus, MS');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('GUC','Gunnison, CO');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('GUM','Guam, TT');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('HDN','Hayden, CO');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('HIB','Hibbing, MN');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('HLN','Helena, MT');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('HNL','Honolulu, HI');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('HOB','Hobbs, NM');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('HOU','Houston, TX');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('HPN','White Plains, NY');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('HRL','Harlingen/San Benito, TX');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('HSV','Huntsville, AL');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('HYS','Hays, KS');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('IAD','Washington, DC');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('IAG','Niagara Falls, NY');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('IAH','Houston, TX');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('ICT','Wichita, KS');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('IDA','Idaho Falls, ID');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('ILM','Wilmington, NC');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('IMT','Iron Mountain/Kingsfd, MI');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('IND','Indianapolis, IN');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('INL','International Falls, MN');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('ISN','Williston, ND');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('ISP','Islip, NY');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('ITH','Ithaca/Cortland, NY');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('ITO','Hilo, HI');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('JAC','Jackson, WY');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('JAN','Jackson/Vicksburg, MS');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('JAX','Jacksonville, FL');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('JFK','New York, NY');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('JLN','Joplin, MO');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('JMS','Jamestown, ND');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('JNU','Juneau, AK');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('KOA','Kona, HI');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('KTN','Ketchikan, AK');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('LAN','Lansing, MI');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('LAR','Laramie, WY');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('LAS','Las Vegas, NV');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('LAW','Lawton/Fort Sill, OK');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('LAX','Los Angeles, CA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('LBB','Lubbock, TX');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('LBE','Latrobe, PA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('LCH','Lake Charles, LA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('LEX','Lexington, KY');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('LFT','Lafayette, LA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('LGA','New York, NY');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('LGB','Long Beach, CA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('LIH','Lihue, HI');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('LIT','Little Rock, AR');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('LNK','Lincoln, NE');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('LRD','Laredo, TX');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('LSE','La Crosse, WI');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('LWS','Lewiston, ID');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('MAF','Midland/Odessa, TX');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('MBS','Saginaw/Bay City/Midland, MI');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('MCI','Kansas City, MO');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('MCO','Orlando, FL');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('MDT','Harrisburg, PA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('MDW','Chicago, IL');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('MEI','Meridian, MS');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('MEM','Memphis, TN');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('MFE','Mission/McAllen/Edinburg, TX');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('MFR','Medford, OR');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('MGM','Montgomery, AL');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('MHT','Manchester, NH');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('MIA','Miami, FL');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('MKE','Milwaukee, WI');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('MKG','Muskegon, MI');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('MLB','Melbourne, FL');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('MLI','Moline, IL');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('MLU','Monroe, LA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('MMH','Mammoth Lakes, CA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('MOB','Mobile, AL');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('MOT','Minot, ND');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('MQT','Marquette, MI');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('MRY','Monterey, CA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('MSN','Madison, WI');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('MSO','Missoula, MT');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('MSP','Minneapolis, MN');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('MSY','New Orleans, LA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('MTJ','Montrose/Delta, CO');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('MYR','Myrtle Beach, SC');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('OAJ','Jacksonville/Camp Lejeune, NC');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('OAK','Oakland, CA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('OGG','Kahului, HI');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('OKC','Oklahoma City, OK');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('OMA','Omaha, NE');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('OME','Nome, AK');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('ONT','Ontario, CA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('ORD','Chicago, IL');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('ORF','Norfolk, VA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('ORH','Worcester, MA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('OTH','North Bend/Coos Bay, OR');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('OTZ','Kotzebue, AK');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('PAH','Paducah, KY');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('PBG','Plattsburgh, NY');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('PBI','West Palm Beach/Palm Beach, FL');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('PDX','Portland, OR');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('PHF','Newport News/Williamsburg, VA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('PHL','Philadelphia, PA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('PHX','Phoenix, AZ');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('PIA','Peoria, IL');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('PIB','Hattiesburg/Laurel, MS');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('PIH','Pocatello, ID');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('PIT','Pittsburgh, PA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('PLN','Pellston, MI');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('PNS','Pensacola, FL');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('PPG','Pago Pago, TT');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('PSC','Pasco/Kennewick/Richland, WA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('PSE','Ponce, PR');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('PSG','Petersburg, AK');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('PSP','Palm Springs, CA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('PVD','Providence, RI');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('PWM','Portland, ME');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('RAP','Rapid City, SD');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('RDD','Redding, CA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('RDM','Bend/Redmond, OR');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('RDU','Raleigh/Durham, NC');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('RHI','Rhinelander, WI');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('RIC','Richmond, VA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('RKS','Rock Springs, WY');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('RNO','Reno, NV');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('ROA','Roanoke, VA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('ROC','Rochester, NY');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('ROW','Roswell, NM');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('RST','Rochester, MN');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('RSW','Fort Myers, FL');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('SAF','Santa Fe, NM');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('SAN','San Diego, CA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('SAT','San Antonio, TX');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('SAV','Savannah, GA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('SBA','Santa Barbara, CA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('SBN','South Bend, IN');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('SBP','San Luis Obispo, CA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('SCC','Deadhorse, AK');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('SCE','State College, PA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('SDF','Louisville, KY');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('SEA','Seattle, WA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('SFO','San Francisco, CA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('SGF','Springfield, MO');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('SGU','St. George, UT');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('SHV','Shreveport, LA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('SIT','Sitka, AK');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('SJC','San Jose, CA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('SJU','San Juan, PR');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('SLC','Salt Lake City, UT');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('SMF','Sacramento, CA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('SMX','Santa Maria, CA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('SNA','Santa Ana, CA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('SPI','Springfield, IL');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('SRQ','Sarasota/Bradenton, FL');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('STL','St. Louis, MO');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('STT','Charlotte Amalie, VI');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('STX','Christiansted, VI');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('SUN','Sun Valley/Hailey/Ketchum, ID');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('SWF','Newburgh/Poughkeepsie, NY');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('SYR','Syracuse, NY');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('TLH','Tallahassee, FL');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('TPA','Tampa, FL');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('TRI','Bristol/Johnson City/Kingsport, TN');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('TTN','Trenton, NJ');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('TUL','Tulsa, OK');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('TUS','Tucson, AZ');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('TVC','Traverse City, MI');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('TWF','Twin Falls, ID');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('TXK','Texarkana, AR');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('TYR','Tyler, TX');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('TYS','Knoxville, TN');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('UST','St. Augustine, FL');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('VLD','Valdosta, GA');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('VPS','Valparaiso, FL');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('WRG','Wrangell, AK');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('XNA','Fayetteville, AR');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('YAK','Yakutat, AK');
Insert into AIRPORTCITY (AIRPORT,CITY) values ('YUM','Yuma, AZ');
